name: blaq_form
description: "A composable, extensible Flutter forms package with prebuilt validations, adaptive field types, and a developer-first API."
version: 0.0.1
homepage: https://github.com/Creative-Blaq-Studios/BlaqForm
repository: https://github.com/Creative-Blaq-Studios/BlaqForm
issue_tracker: https://github.com/Creative-Blaq-Studios/BlaqForm/issues
topics:
  - forms
  - validation
  - widgets
  - input

environment:
  sdk: ^3.11.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
